### ISSUE TITLE
List all doesn't list all versions

### ISSUE THREAD

**Issue by ghostsquad** [twuni/asdf-k9s#1]
## Repro Steps

```
🕙 11:14:45 ❯
└─> asdf plugin-add k9s https://github.com/twuni/asdf-k9s.git


🕙 11:15:33 ❯
└─> asdf list all k9s
0.25.1

🕙 11:15:48 ❯
└─> asdf install k9s 0.27.2
```

## Other details

```
└─> asdf --version
v0.11.1
```

MacOS Ventura 13.1 (22C65)

**Comment by canterberry** [comment]
Something is up with list-all; it works when run directly, but not via asdf. You can still install 0.27.2 (v0.27.0+ is why I put together this plugin as a workaround).

It's possible that 0.25.1 is yet another release archive format.

**Comment by ghostsquad** [comment]
can confirm, `asdf install k9s 0.27.2` works

**Comment by ghostsquad** [comment]
I've updated the issue title and description to indicate the problem with `list all`, as I would not have chosen 0.25.X if I knew it wasn't the latest. Happy to ignore the issue with gzips.

**Comment by ghostsquad** [comment]
You may be interested in this issue: https://github.com/asdf-vm/asdf/issues/1318

I'm looking to standardize aspects of how plugins are created and managed in order solve problems inherent with bash scripts as well as make it even more trivial to add new plugins without the overhead currently involved.

Other related projects:

https://github.com/jdxcode/rtx

https://github.com/hyperupcall/woof

**Comment by canterberry** [comment]
That's a good, productive thread. I haven't seen that. I like the template repo for lowering the barrier to entry for new plugins.

**Comment by canterberry** [comment]
:facepalm: Easy fix -- I forgot that asdf wants plugins' `list-all` to return the sorted versions on a single line. https://github.com/twuni/asdf-k9s/commit/dc8892f0e2fef58d6c81c2e28afceb827782d880 adds `| xargs`.

**Comment by ghostsquad** [comment]
🎉 
```
└─> asdf list all k9s
...
0.25.20
0.25.21
0.26.0
0.26.1
0.26.2
0.26.3
0.26.4
0.26.5
0.26.6
0.26.7
0.27.0
0.27.1
0.27.2
```
